name: Linty
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linty:
    name: Linty
    timeout-minutes: 100
    runs-on: ubuntu-latest
    env:
      EXT_LIB_PATH: xifu-irap/third-party-libraries-for-linty
      PROJECT_NAME: dmx-fw
      LINTY_SCANNER: latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Checkout Third-Party Libraries
        uses: actions/checkout@v4
        with:
          repository: ${{ env.EXT_LIB_PATH }}
          fetch-depth: 0
          token: ${{ secrets.THIRD_PARTY_LIBRARIES_TOKEN }}
          path: ./${{ env.EXT_LIB_PATH }}

      - name: Get Libraries
        run: mv ./${{ env.EXT_LIB_PATH }}/${{ env.PROJECT_NAME }}/* .

      - name: Cache
        id: cache-sonar
        uses: actions/cache@v4
        with:
          path: $HOME/.sonar/cache
          key: sonar
          restore-keys: sonar

      - name: Create cache directory if cache is not restored
        if: steps.cache-sonar.outputs.cache-hit != 'true'
        run: mkdir $HOME/.sonar && mkdir $HOME/.sonar/cache

      - name: Set Linty Analysis parameters
        uses: haya14busa/action-cond@v1
        id: linty_analysis_parameters
        with:
          cond: ${{ github.event.pull_request.number != '' }}
          if_true: -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} -Dsonar.pullrequest.base=${{ github.base_ref }} -Dsonar.pullrequest.branch=${{ github.head_ref }}
          if_false: -Dsonar.branch.name=${GITHUB_REF#refs/*/}

      - name: Run Linty
        run: |
          docker run \
            --rm \
            --user="$(id -u):$(id -g)" \
            -e SONAR_HOST_URL=${{ vars.LINTY_CLOUD_URL }} \
            -e SONAR_TOKEN="${{ secrets.LINTY_SCANNER_TOKEN }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e GITHUB_REPOSITORY_OWNER="$GITHUB_REPOSITORY_OWNER" \
            -e GITHUB_REPOSITORY="$GITHUB_REPOSITORY" \
            -e TABBY_CAD_LICENSE="$TABBY_CAD_LICENSE" \
            -v "$PWD:/usr/src" \
            -v "$HOME/.sonar/cache:/opt/sonar-scanner/.sonar/cache" \
            lintyservices/linty-scanner:${{ env.LINTY_SCANNER }} -Dproject.settings=".linty/linty.properties" \
            ${{ steps.linty_analysis_parameters.outputs.value }}
        env:
          TABBY_CAD_LICENSE: ${{ secrets.TABBY_CAD_LICENSE }}

      - name: Debug
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: |
            .linty/
          include-hidden-files: true
